### PR TITLE
Assorted updates

### PR DESCRIPTION
**Pull request by XhmikosR**
* switch to picocolors
* modernize codebase
* remove es6-promise dependency
* remove lodash.find dependency
* remove lodash.pairs dependency
* remove lodash.zipobject dependency
* enforce LF

Should probably be a major version bump.

Non-whitespace diff: https://github.com/vovacodes/find-duplicate-dependencies/pull/9/files?w=1

/CC @vovacodes

### CODE REVIEW

**Comment by vovacodes** [comment]
@XhmikosR Thanks for the PR, I haven't been using this library myself for quite a while. Would you be interested in maintaining it, I'm happy to give you all the permissions you need on github and npm

**Comment by XhmikosR** [comment]
I don't have time either, I just thought I'd clean it up a bit. I'll mark the PR as draft because I found a little more space for improvement :)

After this is done, if you could merge this and release a new major version, that would be perfect!

**Comment by XhmikosR** [comment]
OK, I think this is now ready. I tried it on a couple of repos, including one that only has devDependencies and the results are the same :)

**Comment by XhmikosR** [comment]
All right, now I'm really done. :)

I switched to ESM too and the only dependency is `npm@6`.

**Comment by XhmikosR** [comment]
Any chance you can merge this and release it as v3.0.0 @vovacodes? If you don't want the ESM switch let me know and I'll drop that patch.

**Review by vovacodes — APPROVED** [review]

**Comment by XhmikosR** [comment]
Thanks! Now a new git tag + npm and we are golden :)

**Comment by vovacodes** [comment]
yeah, I'll merge the other proposed PR and publish shortly

**Comment by XhmikosR** [comment]
I don't think you should merge it TBH. It has conflicts and it introduces wrongfully a new dependency.

Just release what we have so far as v3.0.0 please :)

**Comment by vovacodes** [comment]
yeah I'm going to implement it my way so no worries, not gonna merge the PR directly, should not take more than 15 min

**Comment by XhmikosR** [comment]
BTW it seems that the options are not passed from CLI to main so the `checkDevDependencies` option is not exposed in CLI.

Oh, and we could/should probably return early here https://github.com/vovacodes/find-duplicate-dependencies/blob/master/find-duplicate-dependencies.js#L25 if dependencies is empty; we just need to make sure we are passing undefined/null next so that `Object.entries(catalog)` doesn't fail if there are dependencies :)

**Comment by XhmikosR** [comment]
Oh, and we could/should probably return early here https://github.com/vovacodes/find-duplicate-dependencies/blob/master/find-duplicate-dependencies.js#L25 if dependencies is empty

**Comment by vovacodes** [comment]
Published 3.0 with the `--exclude` option added.

@XhmikosR feel free to propose those changes above, I will publish an update if needed

**Pull request merged**
